export default {
  MAIN_COLOR: "#1C2127",
  WEIGHT_COLOR: "#FFFFFF",
  BLACK_COLOR: "#000000",
  LIGHT_GRAY: "#BEBEBE",
  SECOND_LIGHT_COLOR: "#E6E7E8",
  GRAY_COLOR: "#808080",
  LIGHT_WEIGHT: "#FAFAFF",
  BCKGROUND_GRAY: "#F8F7F7",
  GREEN_COLOR: "#028D4A",
  LINK_COLOR: "#33A8ED",
};
